### Pokémon Vision Example API
@baseUrl = http://localhost:5001/api/v0
@workflowId = pokemon-img

### Execute workflow
# @name executeWorkflow
POST {{baseUrl}}/workflows/{{workflowId}}/executions
Content-Type: application/json
Accept: application/json

{
  "input": {
    "image_url": "https://pokeflip.com/cdn/shop/articles/The_Phenomenal_Firepower_of_Charizard_-_The_Ultimate_Pokemon.jpg"
  }
}

### Get execution details
@execId = {{executeWorkflow.response.body.data.exec_id}}
GET {{baseUrl}}/executions/workflows/{{execId}}
Accept: application/json
